### ISSUE TITLE
Is this package still needed?

### ISSUE THREAD

**Issue by bittner** [ninoseki/uv-sort#14]
I'm fresh on NixOS and discovered [uv-sort](https://search.nixos.org/packages?channel=unstable&show=uv-sort&query=uv) as a potential companion to `uv`. I was surprised to learn that uv doesn't maintain the sort order already.

However, when I tried adding Python packages to a freshly initialized Python project with [uv 0.6.12](https://github.com/astral-sh/uv/releases/tag/0.6.12) I got all dependencies in `pyproject.toml` perfectly sorted.

Does this mean that `uv-sort` is now obsolete, or do I miss something?

**Comment by ninoseki** [comment]
As of v0.6.12, uv does not guarantee the alphabetical order of dependencies.

For example,

```toml
[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["requests>=2.32.3", "httpx>=0.28.1"]
```
(Note: Its alphabetical order is discorted) 

Executing `uv add fastapi` against above pyproject.toml produces:

```toml
dependencies = [
  "requests>=2.32.3",
  "httpx>=0.28.1",
  "fastapi>=0.115.12",
]
```

What I mean is it depends on how to manage pyproject.toml. If you always do `uv add` properly, it will be fine. If you do manual edit on `pyproject.toml` and disort the order, it will be not fine.
