### ISSUE TITLE
Inconsistent sorting precedence between dash and square bracket in dependency names

### ISSUE THREAD

**Issue by AndreaVidali** [ninoseki/uv-sort#18]
Hi,

I discovered a niche bug that affects one of my `pyproject.toml`. The issue is related to the precedence between dashes (-) and square brackets ([]) in dependency names.

Here’s a minimal example to reproduce:

```toml
[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dvc[azure]>=3.59.2",
    "uv-sort>=0.5.1",
]
```

Then I run `uv add dvc-pandas`. This updates the `pyproject.toml` to:

```toml
[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dvc-pandas>=0.3.3",
    "dvc[azure]>=3.59.2",
    "uv-sort>=0.5.1",
]
```
Finally, running `uv-sort`, produces the following output:
```toml
[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dvc[azure]>=3.59.2",
    "dvc-pandas>=0.3.3",
    "uv-sort>=0.5.1",
]
```

To summarize, `uv` adds `dvc-pandas` before `dvc[azure]` (i.e., dash takes precedence), while `uv-sort` reorders them so that `dvc[azure]` comes first (i.e., square bracket takes precedence).

Let me know if you need any further information to reproduce the issue.

Thanks!

Edit: my `uv-sort` version is 0.5.1
